### ISSUE TITLE
What's the difference to virtualenvwrapper?

### ISSUE THREAD

**Issue by alshain** [aperezdc/virtualz#5]
How do I decide whether I want to use virtualenvwrapper rather than your project?

It would be nice if you could add a section to the readme which addresses this.

**Comment by aperezdc** [comment]
I wrote VirtualZ because I grown tired if virtualenvwrapper being often broken under Zsh, and because after trying [VirtualFish](https://github.com/adambrenecki/virtualfish) I knew that something faster that would integrate better with Zsh could be written.

You have a good point about adding a comparison in the README. I'll try to set aside some time to do a writeup :wink:
